# Generated by Django 4.2 on 2024-02-29 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("datetime_start", models.DateTimeField()),
                ("price", models.FloatField()),
                ("max_group_clients", models.IntegerField(default=1)),
                ("min_group_clients", models.IntegerField(default=0)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.author")),
            ],
        ),
        migrations.CreateModel(
            name="ProductClient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="school.client")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="school.product")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="clients",
            field=models.ManyToManyField(related_name="products", through="school.ProductClient", to="school.client"),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("video_url", models.URLField()),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.product")),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("clients", models.ManyToManyField(blank=True, related_name="groups", to="school.client")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.product")),
            ],
        ),
    ]
